CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/templates/configmap.yaml, helm/nginx-ingress-controller-app/values.yaml
Instana needs to use the old port to get the stats. Adding the `http-snippet` to the configmap allows our customer to add it back
=> Add http snippet setting for Instana

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/4795
I've checked all the PRs starting from `-app` repo creation data to sync all changes back. The only one is version. Also updating changelog with the `1.1.0` version, which I'll use for an app release tag.
I'll not tag it until we're ready to App CR migration
=> Sync back from legacy

helm/nginx-ingress-controller-app/values.yaml
These settings seem to have been copied from now deprecated https://github.com/giantswarm/kubernetes-nginx-ingress-controller but they do not seem to be used anywhere.
Uncovered this while working on https://github.com/giantswarm/giantswarm/issues/6817
=> Remove unused default backend configuration

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml, helm/nginx-ingress-controller-app/templates/controller-service-nodeport.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8357
=> Add metrics Service for prometheus-operator support

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-service-aws-loadbalancer.yaml
We offer the option to setup the proxy protocol but to make it work we need to add the annotation in the Kubernetes service of the IC to tell AWS to create the ELB policy that forwards correctly the requests.
=> Add proxy protocol option in the service annotations

CHANGELOG.md, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8664
=> Upgrade to nginx-ingress-controller 0.28.0

CHANGELOG.md, helm/nginx-ingress-controller-app/Configuration.md, helm/nginx-ingress-controller-app/templates/controller-service-nodeport.yaml, helm/nginx-ingress-controller-app/values.yaml, integration/templates/ingress_controller_values.go
While testing legacy AWS WIP release https://github.com/giantswarm/releases/pull/88 a regression (introduced via https://github.com/giantswarm/nginx-ingress-controller-app/pull/12) was observed - nginx NodePort Service installation is being attempted as part of installing App chart, even though for legacy aws (and kvm) clusters one such service gets already created via ignition.
This PR simplifies NodePort Service template in nginx IC App - service enabled flag is disabled by default, and it gets flipped on only for legacy Azure by legacy cluster-operator (see https://github.com/giantswarm/cluster-operator/blob/legacy/service/controller/resource/clusterconfigmap/desired.go#L62-L74)
For aws node pool clusters LoadBalancer Service continues to be installed as before.
In this PR I've bumped …
=> Enable NodePort Service just for legacy Azure tenant clusters

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
nginx IC 0.29.0 was updated from 1.13.1 to most recent go 1.13.8 which among other things includes fixes hardening certificate validation in go's crypto/x509 package (done in Go 1.13.7), which should help nginx IC panic less i.e. better handle (survive) invalid certificates customers configure as in https://github.com/giantswarm/giantswarm/issues/8707
For complete nginx IC 0.29.0 change log see https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md#0290
Go 1.13 release notes can be found at https://golang.org/doc/devel/release.html#go1.13
Plan is to release this as 1.5.0 and include it in legacy WIP releases:
- AWS 9.1.1 giantswarm/releases#88
- KVM 11.1.1 giantswarm/releases#89
- Azure 11.2.0 giantswarm/releases#84
=> Upgrade to nginx-ingress-controller 0.29.0

CHANGELOG.md, helm/nginx-ingress-controller-app/Configuration.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-poddisruptionbudget.yaml, helm/nginx-ingress-controller-app/values.yaml, integration/templates/ingress_controller_values.go
Towards https://github.com/giantswarm/roadmap/issues/65
=> Enable HPA by default

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8676
Used same as in upstream Chart https://github.com/helm/charts/blob/master/stable/nginx-ingress/Chart.yaml#L7
=> Configure app icon

CHANGELOG.md
This release includes:
- Disabling HPA and clearing resource requests for XS clusters https://github.com/giantswarm/nginx-ingress-controller-app/pull/34
This nginx IC App release is to be included in
- AWS 9.0.1
- AWS 9.2.1
- KVM 11.2.1
- Azure 11.2.1
together with cluster-operator 0.23.5 https://github.com/giantswarm/cluster-operator/pull/959
=> Release 1.6.1

CHANGELOG.md, helm/nginx-ingress-controller-app/Configuration.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-hpa.yaml, helm/nginx-ingress-controller-app/templates/rbac.yaml
Towards https://github.com/giantswarm/giantswarm/issues/9379
These config properties were dropped in https://github.com/giantswarm/nginx-ingress-controller-app/pull/26, released in nginx IC App v1.4.0.
=> Reintroduce prematurely dropped deprecated config properties

CHANGELOG.md
This release includes:
- Differentiate resource requests and autoscaling for xxs, xs and s cluster profiles #38
This nginx IC App release is to be included in platform releases:
- AWS 9.0.1
- AWS 9.2.1
- KVM 11.2.1
- Azure 11.2.1
together with cluster-operator 0.23.6 https://github.com/giantswarm/cluster-operator/pull/975
=> Release 1.6.3

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.yaml, integration/templates/ingress_controller_values.go
While testing [kvm 11.2.1 WIP release](https://github.com/giantswarm/releases/pull/139) it was uncovered that small cluster profile (encoded with 3) is not being handled correctly - desired resource requests were not being set. This PR fixes the issue.
=> Fix small cluster profile resource requests

CHANGELOG.md, helm/nginx-ingress-controller-app/Configuration.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/9706 and https://github.com/giantswarm/giantswarm/issues/9884
It applies https://github.com/kubernetes/ingress-nginx/pull/4487#issuecomment-525588554 and https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.26.0
=> Align graceful termination configuration with changes made in upstream ingress-nginx 0.26.0

CHANGELOG.md
Includes:
- Align graceful termination configuration with changes made in upstream ingress-nginx 0.26.0 (https://github.com/giantswarm/nginx-ingress-controller-app/pull/46)
=> Prepare v1.6.7 release

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
Dynamic mode is enabled by default and cannot be turned off, although option is still there but just to display deprecation warning.
=> Remove use of deprecated enable-dynamic-certificates CLI flag

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/8828
Clients like Happa will be taught to look through the sources list for urls ending in README.md, and to display them.
=> Add link to readme in sources.

CHANGELOG.md, helm/nginx-ingress-controller-app/Configuration.md, helm/nginx-ingress-controller-app/values.yaml
Upstream `error-log-level` defaults to `notice` (see https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md#error-log-level) 
Our nginx IC chart had `error-log-level` default overridden to `error` via https://github.com/giantswarm/kubernetes-nginx-ingress-controller/pull/61 i.e. https://github.com/giantswarm/giantswarm/issues/2614 - @jgsqware if you remember please correct me if wrong - IIUC intention of that PR seems to have been to enable access and error logs, while overriding of `error-log-level` from upstream default `notice` to `error` was not really intended.
Anyway, for debugging incidents like:
- https://github.com/giantswarm/giantswarm/issues/9884
- https://github.com/giantswarm/giantswarm/issues/9706
it would help to have …
=> Change default error-log-level from error to notice

CHANGELOG.md
Includes:
- Default max-worker-connections to 0 (https://github.com/giantswarm/nginx-ingress-controller-app/pull/50)
- Change default error-log-level from error to notice (https://github.com/giantswarm/nginx-ingress-controller-app/pull/51)
- Remove use of deprecated enable-dynamic-certificates CLI flag (https://github.com/giantswarm/nginx-ingress-controller-app/pull/49)
- Add link to readme in sources (https://github.com/giantswarm/nginx-ingress-controller-app/pull/48)
=> Prepare v1.6.8 release

integration/templates/ingress_controller_values.go
This stabilizes integration tests - they were running with 1 replica (default adjusted for smallest customer clusters) and only sometimes would scale out to 2 by HPA as exception.
=> Use 2 replicas for integration test

helm/nginx-ingress-controller-app/Chart.yaml
I made a mistake in the Readme URL. Didn't notice that until I tried to open a tagged app as opposed to a test app. Since the test app has some special code that removes the version and uses just the sha.
=> Fix the readme url, it is tagged with a v

CHANGELOG.md
Towards: https://github.com/giantswarm/giantswarm/issues/8877
Includes:
- Make NGINX IC Service `externalTrafficPolicy` configurable and default to `Local` (https://github.com/giantswarm/nginx-ingress-controller-app/pull/71)
=> Prepare release 1.6.10

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-hpa.yaml, helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml, helm/nginx-ingress-controller-app/templates/controller-poddisruptionbudget.yaml, helm/nginx-ingress-controller-app/templates/controller-service-aws-loadbalancer.yaml, helm/nginx-ingress-controller-app/templates/controller-service-nodeport.yaml, helm/nginx-ingress-controller-app/templates/np.yaml, helm/nginx-ingress-controller-app/templates/psp.yaml, helm/nginx-ingress-controller-app/templates/rbac.yaml, integration/test/basic/main_test.go
towards giantswarm/giantswarm/issues/10850
this PR aligns the labels with this change: https://github.com/giantswarm/k8scloudconfig/pull/695/files#diff-4ac7458c2f37b11e62583944d940a2c5
=> align labels with k8scloudconfig

CHANGELOG.md
towards giantswarm/giantswarm/issues/10850
* aligns labels with k8scloudconfig (where possible) (#74)
=> Release v1.6.11

.circleci/config.yml
This makes hold-run-perf-tests job/step top level, so it can be approved, without waiting for integration test to complete.
=> Allow approving perf tests early

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards giantswarm/giantswarm#10197
As follow up to https://github.com/giantswarm/nginx-ingress-controller-app/pull/84, this PR
- makes monitoring headless Service non-optional,
- fixes bug with hardcoded app monitoring port
=> Make monitoring headless Service non-optional

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/9332
public/internal LB choice was supported for AWS node pools since beginning of the repo and 10.* platform releases https://github.com/giantswarm/nginx-ingress-controller-app/pull/4
public/internal LB choice was supported for Azure since 11.4.0 and nginx IC App 1.7.0 via https://github.com/giantswarm/nginx-ingress-controller-app/pull/73
Customers actually need both public and internal.
We do not yet support installing multiple nginx App per TC, multiple ingress classes so one can configure multiple Ingress resources per backend service, one for each kind of clients, i.e. https://github.com/giantswarm/giantswarm/issues/9060 is still TODO
This PR adds support for enabling additional nginx-ingress-controller-internal Service, …
=> Support separate internal LB

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12210
There was a regression in 0.34.0, for more details see https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md#0341
=> Upgrade to ingress-nginx 0.34.1

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/rbac.yaml
This was broken with multi-nginx support.
Previously hardcoded/default election ID was since then made dynamic (for multi-nginx support), based on App i.e. helm release name, while RBAC permission/rule wasn't adjusted.
=> Fix controller RBAC permissions for leader election ConfigMap

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/np.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12642
This was broken with https://github.com/giantswarm/nginx-ingress-controller-app/pull/19
=> Fix NetworkPolicy templating, to allow metrics port scrapes

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrole.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrolebinding.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-createSecret.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/np.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/psp.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/role.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/rolebinding.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/serviceaccount.yaml, helm/nginx-ingress-controller-app/templates/test/test-runner.yaml
NGINX validating webhook has two webhook patching jobs, admission webhook (secret) creation Job run at pre-install/pre-upgrade, and admission webhook patch Job run as post-install/pre-upgrade helm lifecycle phases via helm hook.
Installation was not reliable, sometimes it would fail. It was hard to debug. But today from a failure on a cluster using nginx 1.9.0 we've managed to learn more - secret creation Job was run there before RBAC resources got deployed, without them the Job Pod has no permission to manage Secret resources. I.e. source of unreliable webhook helm hook resource management was missing explicitly assigned weights and lack of guaranteed consistent ordering in Helm 2 when default weight (0) is assigned to all resources installed at helm lifecycle hook phases.
By …
=> Configure helm hook weights

.circleci/config.yml
This PR pins the used `kube-app-testing.sh` script version to the current latest `v0.5.2`. This is done in preparation of upcoming changes in `kube-app-testing.sh`. (giantswarm/kube-app-testing#25)
=> pin kat version to git tag v0.5.2

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/configmap.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12893
We want to install this app into CP
But it requires a way to configure IC with values from catalog
Currently, we have `.Values.configmap`, but we can't put `configmap` option into control-plane catalog configuration. It is too generic.
That's why I'm adding this key
This doesn't look super nice, but we will get rid of it during migration to the new configuration management
=> Extend ingress-controller config with unique key in values

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/14785
This PR:
- adds the ability to disable the updating of ingress loadbalancer status fields
=> allow toggling of the status update flag

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.yaml
This PR:
- adds the ability to control anti-affinity scheduling rule via values.
=> allow control of antiaffinity scheduling via values.yaml

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/252
This PR bumps the used container image version to 0.43.0.
=> Bump container image version to 0.43.0

helm/nginx-ingress-controller-app/templates/controller-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
This PR:
- adds an annotation to the controller service. This will be used by external-dns to limit the resources it reconciles.
See https://github.com/giantswarm/external-dns-app/pull/49
=> Annotate controller service for external-dns

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
This PR:
- allows extra annotations to be added to the controller deployment via the values file.
=> support user-provided annotations 

helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml
=> remove-conflicting-webhook-api-versions

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
Add configuration options for `failurePolicy` and `timeoutSeconds` of validating webhook configuration.
=> Add configuration options to validating webhook

.circleci/config.yml, CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.yaml
This PR upgrades the controller image to 0.48.1
From this point on, the flag `--disable-svc-external-name` flag is  set by default to disable forwarding to [ExternalName Services](https://kubernetes.io/docs/concepts/services-networking/service/#externalname). If you require this feature, you can disable setting this flag through user values by setting `controller.disableExternalNameForwarding` to `true`.
=> Upgrade 0.48.1

CHANGELOG.md
Talked w Gerald, it is unlikely that customers use it in this way, therefore unlikely to be breaking. I want to communicate that to avoid scaring customers of a breaking change.
=> Clarify that the NGINX upgrade is unlikely to be breaking

CHANGELOG.md, README.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/templates/_helpers.tpl, helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-ingressclass.yaml, helm/nginx-ingress-controller-app/templates/rbac.yaml, helm/nginx-ingress-controller-app/tests/abs/Pipfile, helm/nginx-ingress-controller-app/tests/abs/Pipfile.lock, helm/nginx-ingress-controller-app/tests/abs/multi-controller-manifests.yaml, helm/nginx-ingress-controller-app/tests/abs/test-ingress.yaml, helm/nginx-ingress-controller-app/tests/abs/test_basic_cluster.py, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml, test/kind_config.yaml
This PR updates the nginx-ingress-controller-app to use upstream version 1.0.0. It will become Version 2.2.0 of the app.
Important changes:
- Installs a `IngressClass`
- Only works on k8s >= 1.19
- Only works with `Ingress` in version `networking.k8s.io/v1`
=> Upgrade to nginx-ingress-controller v1.0.0

.ats/main.yaml
This PR removes the `2.1.0` version from upgrade tests
=> do not pin upgrade tests to 2.1.0

README.md
The values structure for ingress classes changed in https://github.com/giantswarm/nginx-ingress-controller-app/pull/218/
This caused a problem in kudu when upgrading an internal instance of nginx IC.
See https://gigantic.slack.com/archives/C02LW7LUKUH
=> Add note on values for multiple ingress controllers

.github/pull_request_template.md, CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/19834
This PR upgrades to upstream 1.1.0
=> Use upstream ingress controller version 1.1.0

.ats/main.yaml, .circleci/config.yml, CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml, tests/ats/Pipfile, tests/ats/Pipfile.lock
This PR updates the used ingress controller version to 0.50.0
Hint:
```
```
=> Upgrade controller image to 0.50.0

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml
This PR adds the `giantswarm.io/monitoring-app-label` annotaion to the metrics service. Towards https://github.com/giantswarm/roadmap/issues/601 https://github.com/giantswarm/giantswarm/issues/20023
=> Augment monitoring annotations

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
=> Bump used container version to 1.1.1

CHANGELOG.md, README.md, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml
This PR updates the annotations on services for internal usage.
Hint:
```
```
=> Update aws-load-balancer annotations for internal cluster use

CHANGELOG.md, helm/nginx-ingress-controller-app/values.yaml
This PR changes the kube-webhook-certgen container image with the one used by the upstream ingress-nginx helm chart.
This is to ensure compatibility with kubernetes 1.22
=> Swap kube-webhook-certgen image

.circleci/config.yml, CHANGELOG.md
Push to control plane catalog to use the app from MCs as well
Hint:
```
```
=> Push chart to control plane catalog.

.ats/main.yaml, CHANGELOG.md, helm/nginx-ingress-controller-app/values.yaml
Changelog entry:
> This release contains a potential breaking change in case you are using and relying on the configuration setting [`use-forwarded-headers`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers). From now on the default value will change to `false`. In case you're relying on this feature, you'll need override this in your customized values like this:
>
>     configmap:
>          use-forwarded-headers: "true"
Tests and questioning customers already are already done by @ubergesundheit
=> Disable `use-forwarded-headers` by default

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
Towards a request made by a customer today in support 
Hint:
```
```
=> Make maxSurge configurable

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-hpa.yaml, helm/nginx-ingress-controller-app/templates/controller-poddisruptionbudget.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml, tests/ats/multi-controller-manifests.yaml, tests/test-values.yaml
This PR drops support for cluster profiles since they are not set by either cluster operator nor app operator and therefore the defaults get used. Furthermore it reduces the requests to those from upstream.
Resolves https://github.com/giantswarm/giantswarm/issues/21735.
Hint for KVM:
```
kubectl port-forward -n kube-system …
```
=> Fix: Reduce resource requests.

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
This PR updates the used container image version to [v1.2.1](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.2.1). It mainly contains the removal of nginx [`root`](https://nginx.org/en/docs/http/ngx_http_core_module.html#root) and [`alias`](https://nginx.org/en/docs/http/ngx_http_core_module.html#alias) directives which are not used by the ingress controller because it only proxies.
=> Update used container image to v1.2.1

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
This PR adds support for topologySpreadConstraints.
Hint for KVM:
```
```
=> helm/deployment: Add topologySpreadConstraints.

helm/nginx-ingress-controller-app/values.yaml
Default values are still some kind of optional since they are using `whenUnsatisfiable: ScheduleAnyway` so pods won't be pending.
Hint for KVM:
```
ingress_domain=host.configured.in.ingress; curl --connect-to "$ingress_domain:80:127.0.0.1:8080" …
```
=> helm/values: Enable topologySpreadConstraints by default.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/configmap.yaml, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/22515
This PR attempts to ease installation of the app on management cluster by
- not applying externalDNS annotations on the ingress services if `baseDomain` is not set.
- removing the default value for `baseDomain` configuration value automatically set for workload cluster installations.
- removing unused configuration values for chart installations on management clusters.
=> Remove default basedomain

.circleci/config.yml
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
Hint for KVM:
```
```
=> Added CI job to push to CAPG collection

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Upgrade from previous version | ✓ |  |  |
| Existing Ingress resources are reconciled correctly | ✓ |  |  |
| Fresh install | ✓ |  |  |
| Fresh Ingress resources are reconciled correctly | ✓ |  |  |
Hint for KVM:
```
```
=> templates/controller-metrics-service: Add labels.

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/templates/rbac.yaml, helm/nginx-ingress-controller-app/values.yaml, tests/test-values.yaml
This PR 
- updates the controller image version to v1.3.0
- changes the default number of replicas to 2
- Plain installing works
- Upgrading from previous version works
=> Upgrade controller image version to v1.3.0

README.md
=> Add notes for use of PROXY protocol in AWS by default.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Upgrade from previous version | ✅ |  |  |
| Existing Ingress resources are reconciled correctly | ✅ |  |  |
| Fresh install | ✅ |  |  |
| Fresh Ingress resources are reconciled correctly | ✅ |  |  |
Hint for KVM:
```
```
=> templates/service: Make `loadBalancerSourceRanges` configurable.

CHANGELOG.md, helm/nginx-ingress-controller-app/values.schema.json
This PR adds validation for `controller.service.externalTrafficPolicy` and `controller.service.internal.externalTrafficPolicy` to only allow `Local` and `Cluster`.
=> Add validation for externalTrafficPolicy fields

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Upgrade from previous version | ✅ | ✅ |  |
| Existing Ingress resources are reconciled correctly | ✅ | ✅ |  |
| Fresh install | ✅ | ✅ |  |
| Fresh Ingress resources are reconciled correctly | ✅ | ✅ |  |
Hint for KVM:
```
```
=> chart: Update controller container image to `v1.3.1`.

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/templates/rbac.yaml, helm/nginx-ingress-controller-app/values.yaml
Closes https://github.com/giantswarm/giantswarm/issues/23642.
| Upgrade from previous version | ✅ | ✅ |  |
| Existing Ingress resources are reconciled correctly | ✅ | ✅ |  |
| Fresh install | ✅ | ✅ |  |
| Fresh Ingress resources are reconciled correctly | ✅ | ✅ |  |
Hint for KVM:
```
```
=> Update controller container image to `v1.4.0`.

helm/nginx-ingress-controller-app/Chart.yaml
For https://github.com/giantswarm/roadmap/issues/1248
Hint for KVM:
```
```
=> Add icon to Chart.yml for happa

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/_helpers.tpl, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrole.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrolebinding.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-createSecret.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/np.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/psp.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/role.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/rolebinding.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/serviceaccount.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml, helm/nginx-ingress-controller-app/templates/configmap.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-hpa.yaml, helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml, helm/nginx-ingress-controller-app/templates/controller-poddisruptionbudget.yaml, helm/nginx-ingress-controller-app/templates/controller-service-webhook.yaml, helm/nginx-ingress-controller-app/templates/np.yaml, helm/nginx-ingress-controller-app/templates/psp.yaml, helm/nginx-ingress-controller-app/templates/rbac.yaml, helm/nginx-ingress-controller-app/templates/service-account.yaml
=> Helpers: Rename `resource.default.name` to `ingress-nginx.fullname`.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrole.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrolebinding.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-createSecret.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/psp.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/role.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/rolebinding.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/serviceaccount.yaml
Note for reviewers: Since this PR includes functional changes (hook annotations), I'll also test it thoroughly.
=> Templates: Align hook annotations, namespaces & indention.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-createSecret.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Templates: Add `controller.admissionWebhooks.annotations`.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Test / Provider | AWS |
| --- | --- |
| Upgrade from previous version | ✅ |
| Existing Ingress resources are reconciled correctly | ✅ |
| Fresh install | ✅ |
| Fresh Ingress resources are reconciled correctly | ✅ |
Hint for KVM:
```
```
=> Webhook: Add labels & selectors.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrole.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/psp.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Test / Provider | AWS |
| --- | --- |
| Upgrade from previous version | ✅ |
| Existing Ingress resources are reconciled correctly | ✅ |
| Fresh install | ✅ |
| Fresh Ingress resources are reconciled correctly | ✅ |
Hint for KVM:
```
```
=> Templates: Add `controller.admissionWebhooks.existingPsp`.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/_helpers.tpl, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-createSecret.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/networkpolicy.yaml, helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Upgrade from previous version | ✅ |  |  |
| Existing Ingress resources are reconciled correctly | ✅ |  |  |
| Fresh install | ✅ |  |  |
| Fresh Ingress resources are reconciled correctly | ✅ |  |  |
Hint for KVM:
```
```
=> Webhook: Align values & functions.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-ingressclass.yaml
=> Ingress Class: Align from upstream.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-poddisruptionbudget.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Upgrade from previous version | ✅ |  |  |
| Existing Ingress resources are reconciled correctly | ✅ |  |  |
| Fresh install | ✅ |  |  |
| Fresh Ingress resources are reconciled correctly | ✅ |  |  |
Hint for KVM:
```
```
=> PDB: Align from upstream & add `minAvailable`.

helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Ingress Class: Align to upstream.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-hpa.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> HPA: Make `apiVersion` configurable.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-service-metrics.yaml
This is already done in the `controller-service-webhook.yaml` and the deployment pods have the required label.
| Upgrade from previous version | ✔ |  |  |
| Existing Ingress resources are reconciled correctly | ✔ |  |  |
| Fresh install | ✔ |  |  |
| Fresh Ingress resources are reconciled correctly | ✔ |  |  |
Hint for KVM:
``` …
```
=> Metrics: Add `app.kubernetes.io/component` to selector.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-hpa.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
| Upgrade from previous version | ✔ |  |  |
| Existing Ingress resources are reconciled correctly | ✔ |  |  |
| Fresh install | ✔ |  |  |
| Fresh Ingress resources are reconciled correctly | ✔ |  |  |
Hint for KVM:
```
```
=> HPA: Remove `controller.autoscaling.apiVersion`, use capabilites instead.

.circleci/config.yml
This PR adds `context: architect` to the `push-to-app-collection` job for openstack
=> Use `context: architect` for all jobs in circleCI

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml
This PR contains a fix for the controller service targeting default backend pods if enabled. This was causing some requests to be sent to wrong nodes and pods.
=> Stop targeting default backend pods with the controller service

CHANGELOG.md, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
Move from maxUnavailable: 1 to maxUnavailable: 25% in the Pod Disruption Budget so that the maximum number of unavailable pods scales at the same pace as the cluster does.
=> Move from `maxUnavailable: 1` to `maxUnavailable: 25%`

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/default-backend-deployment.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Default Backend: Add `defaultBackend.updateStrategy` & `defaultBackend.minReadySeconds`.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-keda.yaml
=> Chart: Add KEDA resources.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-prometheusrules.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Chart: Add Prometheus rules.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-servicemonitor.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Chart: Add service monitor.

CHANGELOG.md, helm/nginx-ingress-controller-app/values.yaml
=> Webhook: Update digest of `giantswarm/ingress-nginx-kube-webhook-certgen`.

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/values.yaml
=> Merge v2.24.1 into `main`.

CHANGELOG.md, helm/nginx-ingress-controller-app/values.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
Hint for KVM:
```
```
=> Remove digest, as it changes depending on the registry

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Service: Align to upstream.

CHANGELOG.md, helm/nginx-ingress-controller-app/Chart.yaml, helm/nginx-ingress-controller-app/templates/_helpers.tpl, helm/nginx-ingress-controller-app/templates/controller-daemonset.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-psp.yaml, helm/nginx-ingress-controller-app/values.yaml
| Upgrade from previous version | ✓ |  |  |
| Existing Ingress resources are reconciled correctly | ✓ |  |  |
| Fresh install | ✓ |  |  |
| Fresh Ingress resources are reconciled correctly | ✓ |  |  |
Hint for KVM:
```
```
=> Image: Update to `v1.7.0`.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-daemonset.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
=> DaemonSet: Align to `Deployment` (and vice versa).

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-daemonset.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
=> Deployment/DaemonSet: Remove `cluster-autoscaler.kubernetes.io/safe-to-evict` annotation.

CHANGELOG.md, helm/nginx-ingress-controller-app/README.md, helm/nginx-ingress-controller-app/templates/_params.tpl, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml, tests/test-values.yaml
=> Service: Remove `controller.service.suffix` & `controller.service.internal.suffix`.

helm/nginx-ingress-controller-app/README.md, helm/nginx-ingress-controller-app/values.schema.json
=> Chart: Update README & values schema.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-daemonset.yaml, helm/nginx-ingress-controller-app/templates/controller-deployment.yaml, helm/nginx-ingress-controller-app/templates/controller-service-metrics.yaml
=> Deployment/DaemonSet: Remove duplicate Prometheus annotations.

CHANGELOG.md, helm/nginx-ingress-controller-app/README.md, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
This PR removes those keys from `configmap` which already match their default documented in [here](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/).
Hint for KVM:
```
ingress_domain=host.configured.in.ingress; …
```
=> Values: Remove `configmap` keys matching defaults.

CHANGELOG.md, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml
`service.beta.kubernetes.io/aws-load-balancer-scheme` defaults to `internal` and only applies to AWS Load Balancer Controller, `service.beta.kubernetes.io/azure-load-balancer-mixed-protocols` has been deprecated long ago.
Hint for KVM:
``` …
```
=> Service: Remove deprecated & default annotations.

CHANGELOG.md, helm/nginx-ingress-controller-app/README.md, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml, tests/test-values.yaml
=> Service: Remove default values for `controller.service.nodePorts` & `controller.service.internal.nodePorts`.

CHANGELOG.md, helm/nginx-ingress-controller-app/README.md, helm/nginx-ingress-controller-app/templates/_params.tpl, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Params: Remove `controller.disableExternalNameForwarding`.

CHANGELOG.md, helm/nginx-ingress-controller-app/README.md, helm/nginx-ingress-controller-app/templates/controller-configmap.yaml, helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml, helm/nginx-ingress-controller-app/templates/controller-service.yaml, helm/nginx-ingress-controller-app/values.schema.json, helm/nginx-ingress-controller-app/values.yaml
=> Values: Deprecate `configmap`, use `controller.config` instead.

helm/ingress-nginx/README.md, helm/ingress-nginx/README.md.gotmpl, helm/ingress-nginx/values.yaml
This is a change from upstream.
=> Docs: Rename `nginx ingress controller` to `Ingress-Nginx Controller`.

CHANGELOG.md, helm/ingress-nginx/README.md, helm/ingress-nginx/templates/controller-service-metrics.yaml, helm/ingress-nginx/values.yaml, tests/ats/manifests/other-ingress.yaml, tests/values.yaml
=> Metrics: Use `ServiceMonitor`.

CHANGELOG.md, helm/ingress-nginx/templates/_helpers.tpl, helm/ingress-nginx/templates/controller-daemonset.yaml, helm/ingress-nginx/templates/controller-deployment.yaml
=> OpenTelemetry: Add distroless `init_module`.

CHANGELOG.md, helm/ingress-nginx/templates/controller-deployment.yaml
=> Deployment: Ignore `replicas` with KEDA enabled.

CHANGELOG.md, helm/ingress-nginx/templates/controller-service-internal.yaml, helm/ingress-nginx/templates/controller-service.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28355
The error was
```
Error: YAML parse error on ingress-nginx/templates/controller-service.yaml: error converting YAML to JSON: yaml: line 9: did not find expected alphabetic or numeric character
```
Likely the YAML parser saw `external-dns.alpha.kubernetes.io/hostname: *.bla` and instead wanted to see a YAML anchor name. Quote the label value as a simple fix.
Found while testing on CAPA with live customer configuration taken from v2.x of the app.
---
**none**
=> Service: Fix wildcard subdomain.

CHANGELOG.md, helm/ingress-nginx/README.md, helm/ingress-nginx/templates/_helpers.tpl, helm/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml, helm/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml, helm/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, helm/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml, helm/ingress-nginx/templates/controller-daemonset.yaml, helm/ingress-nginx/templates/controller-deployment.yaml, helm/ingress-nginx/templates/controller-psp.yaml, helm/ingress-nginx/templates/default-backend-deployment.yaml, helm/ingress-nginx/templates/default-backend-psp.yaml, helm/ingress-nginx/values.schema.json, helm/ingress-nginx/values.yaml, vendir.lock.yml
=> Chart: Tighten `securityContext`s and Pod Security Policies.

CHANGELOG.md, helm/ingress-nginx/README.md, helm/ingress-nginx/values.yaml
=> Admission Webhooks: Update `kube-webhook-certgen` image to `v20231011-8b53cabe0`.

CHANGELOG.md, helm/ingress-nginx/README.md, helm/ingress-nginx/values.yaml
=> Values: Enable `controller.enableAnnotationValidations` by default.

tests/e2e/config.yaml
Explicitly define the CAPI providers to run E2E tests against from PR triggers.
/run app-test-suites
=> Explicitly list the providers to test against

CHANGELOG.md, tests/e2e/go.mod, tests/e2e/go.sum, tests/e2e/suites/basic/basic_suite_test.go
This PR:
- Updates `apptest-framework` to v1.0.0 that now handles cluster creation within the test framework
Closes https://github.com/giantswarm/giantswarm/issues/30663
---
=> Bump apptest-framework to v1.0.0

CHANGELOG.md, tests/e2e/suites/basic/hello_world.go
This PR:
- Uses the values from the cluster chart to get the baseDomain property instead of from the default-apps values. This should allow up to then get rid of the DefaultAppsValues type from clustertest.
This will make things easier when we migrate away from having default-apps.
Related: https://github.com/giantswarm/cluster-test-suites/pull/291
---
/run app-test-suites
=> Get baseDomain from cluster values instead of default-apps

renovate.json5
Signed-off-by: Matias Charriere <matias@giantswarm.io>
This PR:
- Add renovate preset for e2e tests
---
=> Add renovate preset for e2e tests
