giantswarm/ingress-nginx-app

- helm/nginx-ingress-controller-app/Configuration.md
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/4795
> Make ingress class configurable

- .circleci/config.yml
- README.md
Towards https://github.com/giantswarm/giantswarm/issues/4795
> Push to default catalog

- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/cluster-operator/pull/773
> Use ic specific replicas config path

- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-aws-loadbalancer.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-nodeport.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards migration to the app cr
> Add legacy support for chart

- .circleci/config.yml
- CHANGELOG.md
- helm/nginx-ingress-controller-app/Chart.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8353
> Update to nginx IC 0.27.0

- CHANGELOG.md
- helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8353
> Update to nginx IC 0.27.1

- CHANGELOG.md
- helm/nginx-ingress-controller-app/Chart.yaml
- helm/nginx-ingress-controller-app/Configuration.md
- helm/nginx-ingress-controller-app/templates/configmap.yaml
- helm/nginx-ingress-controller-app/values.yaml
Allow override of ssl-protocols
> Allow override of SSL protocols

- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/8664
> Fix 1.3.0 changelog, separate it from 1.2.1 release

- CHANGELOG.md
Includes:
- Disabling HPA for xs clusters https://github.com/giantswarm/nginx-ingress-controller-app/pull/40
> Release 1.6.4

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
Towards https://github.com/giantswarm/roadmap/issues/30
> Change deployment to use release revision not time for Helm 3 support

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/psp.yaml
Restricts volumes to only those required by nginx.
> restrict volumes to only those required

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/psp.yaml
- helm/nginx-ingress-controller-app/values.yaml
> Restore sysctl initcontainer

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-service-aws-loadbalancer.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-nodeport.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/8877
> Make externalTrafficPolicy configurable and default to Local

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/11182
> Make healthcheck probes configurable and liveness probe more resilient

- CHANGELOG.md
Towards giantswarm/giantswarm#11182
> Prepare release 1.6.12

- CHANGELOG.md
- helm/nginx-ingress-controller-app/Chart.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards:
- https://github.com/giantswarm/giantswarm/issues/11530
- https://github.com/giantswarm/giantswarm/issues/10406
> Upgrade to ingress-nginx 0.33.0

- CHANGELOG.md
Includes:
- Manage nginx LB Service on Azure
- Upgrade to ingress-nginx 0.33.0
> Prepare release 1.7.0

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml
- helm/nginx-ingress-controller-app/values.yaml
- integration/test/basic/main_test.go
Towards https://github.com/giantswarm/giantswarm/issues/10197
> Enable app monitoring

- CHANGELOG.md
Towards giantswarm/giantswarm#10197 and giantswarm/giantswarm#9332
> Release 1.7.1

- CHANGELOG.md
- helm/nginx-ingress-controller-app/ci/test-values.yaml
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/controller-hpa.yaml
- helm/nginx-ingress-controller-app/templates/rbac.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12310
> Drop deprecated configuration properties

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12188
> Make node ports configurable

- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/12881
> Cover 1.8.0 breaking changes in changelog

- .github/pull_request_template.md
- CODEOWNERS
> Add codeowners file

- objectives.md
Towards https://github.com/giantswarm/giantswarm/issues/12320 we want to make it clear what we do vs don't do. This is reproduction of meeting ([notes](https://docs.google.com/document/d/16LMwwXChi1UudLp62eCygABAuDVS5mz8FTl_-qj25XI/edit)) between me, @sslavic , and @piontec sorry it took so long to put here ✌️
> Create NGINX objectives.md

- helm/nginx-ingress-controller-app/Chart.yaml
This updates the app icon to use our static web assets server.
> Update app icon

- .github/workflows/zz_generated.create_release_pr.yaml
> test fixing path in workflow

- .github/workflows/zz_generated.create_release_pr.yaml
> Revert "test fixing path in workflow (#135)"

- .abs/main.yaml
- .circleci/config.yml
Please ignore for now. I wanted to test this on a repo with a `values.schema.json`
> try packaging with abs

- README.md
> Remove out of date limitations

- CHANGELOG.md
Forgot to write a changelog entry for the values.schema.json addition.
> Add changelog entry for values.schema.json

- CHANGELOG.md
> correct header syntax

- .circleci/config.yml
> Use updated architect-orb for updated app-build-suite

- .github/workflows/check_values_schema.yaml
- helm/nginx-ingress-controller-app/values.schema.json
just cleaning up some things i found
> cleanup values schema

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
This PR:
- allows wildcard `*` subdomains to be used.
> quote the external-dns hostname to avoid yaml templating issues

- helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml
> Remove unecessary annotation

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
Look up from upstream:
- [controller-service.yaml](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-service.yaml#L5-L14)
- [values.yaml](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml#L361-L362)
> Pass through annotations and labels to the controller service

- .circleci/config.yml
- CHANGELOG.md
- helm/nginx-ingress-controller-app/.kube-linter.yaml
- helm/nginx-ingress-controller-app/Chart.yaml
- helm/nginx-ingress-controller-app/values.yaml
This PR upgrades the nginx ingress controller image to 0.47.0
> Upgrade nginx image

- .gitignore
- tests/ats/Pipfile
- tests/ats/Pipfile.lock
- tests/ats/test_basic_cluster.py
Tests run successfully for me:
```
./dabs.sh -c helm/nginx-ingress-controller-app
```
> Update Python dependencies

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
> Allow setting LB Service name suffix

- .circleci/config.yml
> Push to openstack-app-collection

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/_helpers.tpl
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- tests/test-values.yaml
> Fix LB Service name suffix

- .circleci/config.yml
> Fix push-to-app-collection CI job settings

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
> Allow disabling external-dns annotations

- .circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/20866
> Push to OCI registry

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/_helpers.tpl
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
Closes https://github.com/giantswarm/giantswarm/issues/22703.
| Upgrade from previous version | ✔️ |  |  |
| Existing Ingress resources are reconciled correctly | ✔️ |  |  |
| Fresh install | ✔️ |  |  |
| Fresh Ingress resources are reconciled correctly | ✔️ |  |  |
Hint for KVM:
```
```
> Feature: Align controller services.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
This PR updates the initContainer version to 3.15.5
> update initContainer to v3.15.5

- README.md
This PR edits the README.md, replacing a relative link with an absolute link, so that it works on happa
> change relative link to absolute link

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.yaml
We want to deploy this app in our GCP clusters too, so we need to support creating internal Load Balancers on GCP.
> Add support for gcp

- .circleci/config.yml
- CHANGELOG.md
- README.md
- helm/nginx-ingress-controller-app/values.yaml
- objectives.md
Also updates upstream references since they already renamed a while ago.
> Repository: Rename `master` to `main`.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/_helpers.tpl
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrole.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-createSecret.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/np.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/psp.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/role.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/rolebinding.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/serviceaccount.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml
- helm/nginx-ingress-controller-app/templates/configmap.yaml
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/controller-hpa.yaml
- helm/nginx-ingress-controller-app/templates/controller-ingressclass.yaml
- helm/nginx-ingress-controller-app/templates/controller-metrics-service.yaml
- helm/nginx-ingress-controller-app/templates/controller-poddisruptionbudget.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-webhook.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/templates/np.yaml
- helm/nginx-ingress-controller-app/templates/psp.yaml
- helm/nginx-ingress-controller-app/templates/rbac.yaml
- helm/nginx-ingress-controller-app/templates/service-account.yaml
> Helpers: Rename `labels.common` to `ingress-nginx.labels`.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/np.yaml
Forgot them in https://github.com/giantswarm/nginx-ingress-controller-app/pull/359.
> Templates: Align hook annotations.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrole.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-createSecret.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/psp.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/role.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/rolebinding.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/serviceaccount.yaml
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
Note for reviewers: Since this PR includes functional changes (hook annotations), I'll also test it thoroughly.
> Templates: Add `controller.admissionWebhooks.patch.labels`.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/admission-webhooks/validating-webhook.yaml
There is no functional change in here, only `matchPolicy: Equivalent` added and indention / ordering fixed to match upstream.
> Templates: Align `ValidatingWebhookConfiguration`.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/networkpolicy.yaml
- helm/nginx-ingress-controller-app/templates/admission-webhooks/job-patch/role.yaml
- helm/nginx-ingress-controller-app/values.yaml
> Admission Webhooks: Align from upstream.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-service-webhook.yaml
- helm/nginx-ingress-controller-app/values.schema.json
| Upgrade from previous version | ✅ |  |  |
| Existing Ingress resources are reconciled correctly | ✅ |  |  |
| Fresh install | ✅ |  |  |
| Fresh Ingress resources are reconciled correctly | ✅ |  |  |
Hint for KVM:
```
```
> Webhook: Align to upstream.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
> Ingress Class: Align to upstream.

- README.md
> Replace dead link

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/configmap.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.yaml
- objectives.md
allow private  ingress also on capa provider
> add-capa-provider

- helm/nginx-ingress-controller-app/values.yaml
> Metrics: Add docs.

- helm/nginx-ingress-controller-app/values.yaml
> Values: Fix comment on metrics service labels.

- helm/nginx-ingress-controller-app/templates/controller-configmap.yaml
> ConfigMap: Align indention.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/_helpers.tpl
- helm/nginx-ingress-controller-app/templates/_params.tpl
- helm/nginx-ingress-controller-app/templates/controller-deployment.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/templates/controller-service.yaml
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
> Helpers: Align to upstream.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/.helmignore
- helm/nginx-ingress-controller-app/Chart.yaml
- helm/nginx-ingress-controller-app/templates/NOTES.txt
> Chart: Align to upstream.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-hpa.yaml
- helm/nginx-ingress-controller-app/templates/default-backend-hpa.yaml
> HPA: Use capabilities, reorder `if`.

- helm/nginx-ingress-controller-app/README.md
- helm/nginx-ingress-controller-app/README.md.gotmpl
> Chart: Improve README.

- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
> Internal Service: Align templating.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/_params.tpl
- helm/nginx-ingress-controller-app/values.yaml
> Params: Align to upstream.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/values.yaml
Fixes https://github.com/giantswarm/giantswarm/issues/26571.
Hint for KVM:
```
```
> Values: Align CPU & memory requests to actual needs.

- .github/pull_request_template.md
> GitHub: Rework pull request template.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/templates/controller-hpa.yaml
- helm/nginx-ingress-controller-app/templates/default-backend-hpa.yaml
> HPA: Align to upstream.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/README.md
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/values.schema.json
- helm/nginx-ingress-controller-app/values.yaml
> Service: Align features from external service to internal one.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/README.md
- helm/nginx-ingress-controller-app/ci/deployment-internal-lb-values.yaml
- helm/nginx-ingress-controller-app/templates/controller-service-internal.yaml
- helm/nginx-ingress-controller-app/values.yaml
> Service: Add `controller.service.internal.ports` & `controller.service.internal.targetPorts`.

- helm/nginx-ingress-controller-app/values.schema.json
> Values: Re-generate `values.schema.json`.

- CHANGELOG.md
- helm/nginx-ingress-controller-app/Chart.yaml
- helm/nginx-ingress-controller-app/README.md
- helm/nginx-ingress-controller-app/values.yaml
> Image: Update to `v1.7.1`.

- .ats/main.yaml
> Tests: Re-enable upgrade tests.

- CHANGELOG.md
- helm/ingress-nginx/templates/controller-poddisruptionbudget.yaml
> PDB: Add `controller.annotations`.

- .circleci/config.yml
- CHANGELOG.md
- helm/nginx-ingress-controller-app/.kube-linter.yaml
- helm/nginx-ingress-controller-app/values.yaml
> Jobs: Remove image digest.

- README.md
- migration.md
I removed a lot of old stuff not applying to the current version and/or our current product anymore. Also I reordered some sections and updated names and configuration values.
Maybe it's easier to just take a look at the [old `README.md`](https://github.com/giantswarm/ingress-nginx-app/blob/v3.0.0-alpha1/README.md) and compare it to the [new one](https://github.com/giantswarm/ingress-nginx-app/blob/pull/480/README.md) without checking the `git diff`.
> Docs: Rework `README.md`.

- CHANGELOG.md
- helm/ingress-nginx/README.md
- helm/ingress-nginx/templates/controller-poddisruptionbudget.yaml
- helm/ingress-nginx/values.yaml
> PDB: Improve checks.

- CHANGELOG.md
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
> Images: Update OpenTelemetry & `kube-webhook-certgen` image.

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
> Image: Update to `v1.8.0`.

- CHANGELOG.md
- helm/ingress-nginx/templates/controller-hpa.yaml
> HPA: Partially revert #465.

- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
> Values: Update comments.

- CHANGELOG.md
> CHANGELOG: Fix links.

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
> Chart: Add logo.

- helm/ingress-nginx/templates/controller-service-internal.yaml
- helm/ingress-nginx/templates/controller-service.yaml
> Service: Omit `toYaml` for `loadBalancerClass`.

- .circleci/config.yml
- tests/ats/Pipfile
- tests/ats/manifests/other-ingress.yaml
- tests/ats/test_ingress.py
- tests/values.yaml
> Tests: Upgrade `app-test-suite` and Python dependencies.

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
> Image: Update to `v1.8.1`.

- CHANGELOG.md
- vendir.yml
> Repository: Implement `vendir` sync.

- CHANGELOG.md
- vendir.yml
> Vendir: Ignore paths.

- CHANGELOG.md
- helm/ingress-nginx/templates/controller-service-internal.yaml
- helm/ingress-nginx/templates/controller-service.yaml
> Service: Template annotations.

- CHANGELOG.md
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
> Values: Update docs about `controller.enableTopologyAwareRouting`.

- CHANGELOG.md
- helm/ingress-nginx/README.md
- helm/ingress-nginx/templates/controller-daemonset.yaml
- helm/ingress-nginx/templates/controller-deployment.yaml
- helm/ingress-nginx/values.yaml
> Deployment/DaemonSet: Add `controller.hostAliases`.

- CHANGELOG.md
- helm/ingress-nginx/README.md
- helm/ingress-nginx/templates/controller-daemonset.yaml
- helm/ingress-nginx/templates/controller-deployment.yaml
- helm/ingress-nginx/values.yaml
> OpenTelemetry: Update image to `v20230721-3e2062ee5`.

- CHANGELOG.md
- helm/ingress-nginx/templates/controller-servicemonitor.yaml
> ServiceMonitor: Explicitly set namespace.

- CHANGELOG.md
- helm/ingress-nginx/templates/controller-serviceaccount.yaml
> Service Account: Align annotation format.

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
> Image: Update to `v1.8.2`.

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
- helm/ingress-nginx/README.md
- helm/ingress-nginx/templates/_helpers.tpl
- helm/ingress-nginx/templates/_params.tpl
- helm/ingress-nginx/templates/controller-daemonset.yaml
- helm/ingress-nginx/templates/controller-deployment.yaml
- helm/ingress-nginx/values.schema.json
- helm/ingress-nginx/values.yaml
- vendir.lock.yml
> Chart: Sync to upstream.

- .circleci/config.yml
- CHANGELOG.md
- tests/ats/Pipfile
> Tests: Upgrade dependencies & remove explicit ATS version.

- CHANGELOG.md
- helm/ingress-nginx/README.md
- helm/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
- helm/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml
- helm/ingress-nginx/templates/controller-psp.yaml
- helm/ingress-nginx/templates/controller-role.yaml
- helm/ingress-nginx/templates/default-backend-psp.yaml
- helm/ingress-nginx/templates/default-backend-role.yaml
- helm/ingress-nginx/templates/default-backend-rolebinding.yaml
- helm/ingress-nginx/values.schema.json
- helm/ingress-nginx/values.yaml
> Values: Add `global.podSecurityStandards.enforced`.

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
> Image: Update to `v1.8.4`.

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
- vendir.lock.yml
> Image: Update to `v1.9.4`.

- tests/ats/test_app.py
- tests/cluster.yaml
> Tests: Make 'em less flaky.

- tests/ats/Pipfile
> Tests: Remove explicit `requests` dependency.

- .circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/28509.
> CircleCI: Push to app collections.

- CHANGELOG.md
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/3040
> Adopt gsoci.azurecr.io oci registry

- helm/ingress-nginx/tests/controller-service_test.yaml
- helm/ingress-nginx/tests/default-backend-extra-configmaps_test.yaml
> Chart: Align tests.

- helm/ingress-nginx/values.yaml
> Values: Revert indentation to upstream.

- CHANGELOG.md
- helm/ingress-nginx/templates/controller-service-internal.yaml
- helm/ingress-nginx/templates/controller-service.yaml
> Service: Add CAPZ support.

- CHANGELOG.md
- migration.md
> Migration: Document caveat regarding `ValidatingWebhookConfiguration`.

- CHANGELOG.md
This PR:
- _Adds/changes/fixes/removes ..._
---
> Remove test-specific changelog entries

- CHANGELOG.md
- helm/ingress-nginx/Chart.yaml
- helm/ingress-nginx/README.md
- helm/ingress-nginx/values.yaml
This PR updates the controller image to [`v1.10.1`](https://github.com/kubernetes/ingress-nginx/blob/main/changelog/controller-1.10.1.md).
---
> Controller: Update image to `v1.10.1`.

- .circleci/config.yml
Disable push to app collections as preparation of a major release containing potentially breaking changes.
> CircleCI: Disable push to app collections.

- .circleci/config.yml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
This PR:
- Restores push to app-collections.
Towards https://github.com/giantswarm/giantswarm/issues/33329
---
> Restore push to app-collections
